apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bountybot.fullname" . }}
  labels:
    {{- include "bountybot.labels" . | nindent 4 }}
type: Opaque
data:
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  gemini-api-key: {{ .Values.secrets.geminiApiKey | b64enc | quote }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  redis-url: {{ .Values.secrets.redisUrl | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}

